version: '3'
services:
  db-telegram:
    image: postgres
    restart: always
    env_file:
      - .env.telegram
    container_name: pg-telegram
    ports:
      #      - "127.0.0.1:5432:5432"
      - '5430:5432' # open host for superset purposes
    volumes:
      - ./pgdata-telegramm:/var/lib/postgresql/data
  db-gpt:
    image: postgres
    restart: always
    env_file:
      - .env.gpt
    container_name: pg-gpt
    ports:
      #      - "127.0.0.1:5432:5432"
      - '5433:5432' # open host for superset purposes
    volumes:
      - ./pgdata-gpt:/var/lib/postgresql/data
  rabbitmq:
    restart: always
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_node'
    ports:
      - 5672:5672
      - 15672:15672
  telegram:
    image: bogdanmarchukv/telegram-gpt:v1.0.1
    restart: always
    container_name: telegram_node
    links:
      - db-telegram
    env_file:
      - .env.telegram
    command: npm run start:prod
    depends_on:
      - db-telegram
      - rabbitmq
  gpt:
    image: bogdanmarchukv/gpt-node:v1.0.1
    restart: always
    container_name: gpt-node
    links:
      - db-gpt
    env_file:
      - .env.gpt
    command: npm run start:prod
    depends_on:
      - db-gpt
      - rabbitmq

volumes:
  pgdata-telegramm:
    driver: local
  pgdata-gpt:
    driver: local
